### ISSUE TITLE
Question: Was the OFP code generated or hand coded?

### ISSUE THREAD

**Issue by samribeiro** [netrack/openflow#113]
Curious =)

**Comment by ybubnov** [comment]
@samribeiro, thank you for the question. Unfortunately that package is written manually. I have been thinking about an auto-generated approach, but all such attempts faced the need of additional domain-specific language or at least schema definition on top of existing makeup languages, like JSON or XML, which can sufficiently describe variable padding in the messages and irregular structure of OpenFlow messages.

This is the main motivation that moves the development of this library, additionally I came up with extensive usage of reflection. I understand the performance implications of such decision, but clear understanding of the library sources was on the first place.

One more point for manual writing is a friendly API (which, I hope, is achieved with a certain success), that, to my mind, cannot be accomplished with auto-generated process.
