### ISSUE TITLE
Double counting in table.go

### ISSUE THREAD

**Issue by samribeiro** [netrack/openflow#119]
Is this double counting?

`
	nn, err := encoding.WriteSliceTo(w, xms)
	if n += nn; err != nil {
		return n + nn, err      <------------
	}
`
https://github.com/netrack/openflow/blob/master/ofp/table.go#L324

Only happens on error. But I am curious if there is a purpose? If so I can send a fix, have it ready.

**Comment by ybubnov** [comment]
Right, it should add the returned length only once, clearly a bug.
