### ISSUE TITLE
consolidate package naming to either "of" or "openflow"

### ISSUE THREAD

**Issue by samribeiro** [netrack/openflow#70]
I suggest "openflow".
If other packages want to use a shorter name they can name the import:
of "netrack/openflow"

one strange example is "ofputil/handler.go" where it imports "openflow", but the package is defined as "of".

**Comment by ybubnov** [comment]
@samribeiro, agreed with the suggestion, the ```openflow``` name is less confusing. Changes ought to assume an update of ```README.md``` file as well.

**Comment by ybubnov** [comment]
closed by #71 and #72
